use_default_settings: true
search:
  formats:
    - html
    - json
server:
  bind_address: "0.0.0.0"
  port: 8080
  base_url: "http://agentanywhere-r1-searxng:8080/"
  limiter: false
  public_instance: false
