FROM oven/bun:1.3.10-slim@sha256:5d5863f35ad9b3acceee8dc134fb2b89f07831129eaeec81af2b19a23dabe3e0 AS build
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY src ./src
COPY index.html vite.config.ts tsconfig.json ./
RUN bun run build

FROM oven/bun:1.3.10-slim@sha256:5d5863f35ad9b3acceee8dc134fb2b89f07831129eaeec81af2b19a23dabe3e0
WORKDIR /app
COPY --from=build /app/src ./src
COPY --from=build /app/dist ./dist
USER bun
CMD ["bun", "src/server.ts"]
