FROM oven/bun:1.4.2-slim@sha256:cb3bbbb08e13a4a2ff400f24c7a2a1d5efa83f6ef8544d52d95a519631e2fc61 AS build
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY src ./src
COPY index.html vite.config.ts tsconfig.json ./
RUN bun run build

FROM oven/bun:1.4.2-slim@sha256:cb3bbbb08e13a4a2ff400f24c7a2a1d5efa83f6ef8544d52d95a519631e2fc61
WORKDIR /app
COPY --from=build /app/src ./src
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY licenses ./licenses
USER bun
CMD ["bun", "src/server.ts"]
